app/authentication/routes.py
from forms import UserLoginForm
from models import User, db, check_password_hash
from flask import Blueprint, render_template, request, redirect, url_for, flash

#imports for flask login
from flask_login import login_user, logout_user, LoginManager, current_user, login_required 

auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

##SIGNUP METHOD

@auth.route('/signup', methods = ['GET', 'POST']) #This are HTML methods to request and submit user data to the servers
def signup():
    form = UserLoginForm() #This comes from 'forms.py' and instantiates the class in that file (see file)

    try:
        if request.method == 'POST' and form.validate_on_submit(): #validate_on_submit comes from forms.py from the import wtfforms.validators
                                                                    #POST means that user submitted that data
            email = form.email.data #This type of information like email and password was entered in the forms.html and ran through forms.py for 
                                    #validation and then if its valid, it will be stored in the 'email' variable. Hence 'form' coming from the (html), etc
            password = form.password.data # same thing for password
            print(email, password)

            user = User(email, password = password) #We are instantiating the 'User' class from models.py

            db.session.add(user)
            db.session.commit()

            flash(f'You have succesfully created a user account {email}', 'User-created') #flash is part of flask. Its for a quick message at the end 
                                                                                # of a request once
            return redirect(url_for('site-home')) #this will redirect and url-for will go and look for 'site' in site/routes.py/home
            #In this case , after the user has created their account, they qwill be redirtected to the home page
    except:
        raise Exception('Invalid for data: Please check your form')
    return render_template('sign_up.html', form = form) #It will redirect the user to the signup form(html) for the data to be verified through
                                                        #forms.py once again. Itll keep asking the user for valid data

###SIGNIN METHOD

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit(): #same verification process as in our 'SIGNUP METHOD' above
            email = form.email.data
            password = form.password.data
            print(email, password)

            logged_user = User.query.filter(User.email == email).first() #here we are taking the email and check it against the 'User' class in mopdels.py
                                                                        #and query our database, filter the data and pull the 'first()' user with that email,
                                                                        #and this will be our logged user and hold on to this user. Should pull back 1 acct

            if logged_user and check_password_hash(logged_user.password, password): #chk_pass_hash takes 2 parameters 1. the hashed pass from user when they
                                                                #signed up, then de-hash it and, 2. the passwrd they are entering now and compare them both 
                                                                #and see if it is accurate. check if the credentials are correct.
                                                                #Also, 'if looged_user' (TRUE statement) is checking if the email is in the datebase. If not ,
                                                                #this 'if-statement' would be false to begin with.
                login_user(logged_user) #We imported from flask_login and passed the variable above in line 50
                flash('You were succesful in your initiation. Congratulations, and welcome to the Jedi Knights', 'auth-success')
                return redirect(url_for('site-profile'))
            else:
                flash('You have failed in your attempt to access this content.', 'auth-failed')
    except:
        raise Exception('Invalid form data: Please check your form')
    return render_template('sign_in.html', form = form)


##LOGOUT METHOD

@auth.route('/logout')
def logout():
    logout_user() #this is another method part of flask
    return redirect(url_for('site.home')) #sending user back to home after being logged out
        

app/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, template_folder = 'site_templates') #The variable 'site'
                                            #is importing the contents of 'site_templates' as it is 
                                            #one of the arguments for the instatiation of the Blueprint class as 'site'.
                                            #This is being called in our file '__init__' on line 5

# this file determines how the page will ultimately end up being rendered. All these file are inside the 'site' folder. This is the 
# 'idea' of the website but it wont do anything until it is called by '__init__.py'. So basically the line of code on line 3 , it is the instatiation
# or blueprint of the website, just like a class in python

@site.route('/')
def home():
    return render_template('index.html') #When we run flask this is our default page wil load index.html with our base.html built around it 

# We are coming from '__init__.py' and the above code is 'home'. It renders 'index.html' along with 'base.html'

@site.route('/profile')
def profile():
    return render_template('profile.html')

app/templates/base.html
<!-- This page is the frame for all pages with for example the nav bar and footing and other aspects of the page that we like them to be present
on every page of our app. Inside this page , on line 47 through 49, we can see where we are going to insert the other objects or other pages by using 
JINJA -->

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Phonebook</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 fixed-top">
        <div class="container">
            <a href="{{ url_for('site.home')}}" class="navbar-brand">Phonebook</a>
            <button 
                class="navbar-toggler" 
                type="button" 
                data-bs-toggle="collapse" 
                data-bs-target="#navmenu"
            ><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navmenu">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a href="{{ url_for('site.home')}}" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('site.profile')}}" class="nav-link">Profile</a>
                    </li>
                    <!-- With the if-statement below, if TRUE, it will show 'logout'. If not or 'else', it will show 'signin/signup' -->
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout')}}" class="nav-link">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signin')}}" class="nav-link">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.signup')}}" class="nav-link">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
<!-- Mysterious placeholder comment! -->
{% block content %}
{% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>
</html>

app/templates/forms.html
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = 'form-control', placeholder = 'place email here ') }}
        </fieldset>
    </div>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place password here ") }}
        </fieldset>

        <!-- Submit button area -->
        {{ form.submit_button(class = "btn btn-primary btn-block mt-2")}}

</form>